CREATE OR REPLACE PROCEDURE DB.SCHEMA.LOAD_TARGET_TABLE_FROM_SOURCE()
RETURNS VARCHAR()
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    STREAM_STALE_STATUS BOOLEAN;
BEGIN
    
    MERGE INTO DB.SCHEMA.TARGET_TABLE --UPDATE ON EXISTING RECORD.
    USING (
            SELECT
                *
            FROM 
                DB.SCHEMA.SOURCE_TABLE
            ) AS SOURCE_TABLE
                ON SOURCE_TABLE.LOAN_NUMBER = TARGET_TABLE.LOAN_NUMBER AND TARGET_TABLE.IS_ACTIVE = TRUE
    WHEN MATCHED 
        AND (SOURCE_TABLE.CUSTOMER_NAME <> TARGET_TABLE.CUSTOMER_NAME 
            OR SOURCE_TABLE.LOAN_AMOUNT <> TARGET_TABLE.LOAN_AMOUNT 
            OR SOURCE_TABLE.LOAN_START_DATE <> TARGET_TABLE.LOAN_START_DATE
            OR SOURCE_TABLE.LOAN_STATUS <> TARGET_TABLE.LOAN_STATUS )
        THEN 
            UPDATE SET
                TARGET_TABLE.IS_ACTIVE       = FALSE,
                TARGET_TABLE.RECORD_END_DATE = CURRENT_TIMESTAMP()

    WHEN NOT MATCHED 
    THEN
        INSERT 
        (
            TARGET_TABLE.LOAN_NUMBER,      
            TARGET_TABLE.CUSTOMER_NAME ,   
            TARGET_TABLE.LOAN_AMOUNT,      
            TARGET_TABLE.LOAN_START_DATE,  
            TARGET_TABLE.LOAN_STATUS,  
            TARGET_TABLE.IS_ACTIVE,        
            TARGET_TABLE.RECORD_BEGIN_DATE,
            TARGET_TABLE.RECORD_END_DATE
        )
        VALUES 
        (
            SOURCE_TABLE.LOAN_NUMBER,      
            SOURCE_TABLE.CUSTOMER_NAME ,   
            SOURCE_TABLE.LOAN_AMOUNT,      
            SOURCE_TABLE.LOAN_START_DATE,  
            SOURCE_TABLE.LOAN_STATUS,      

            TRUE,        
            CURRENT_TIMESTAMP(),
            NULL
        );

    INSERT INTO DB.SCHEMA.TARGET_TABLE ---Insertung new records for the records which we deactivated
    (
        TARGET_TABLE.LOAN_NUMBER,      
        TARGET_TABLE.CUSTOMER_NAME ,   
        TARGET_TABLE.LOAN_AMOUNT,      
        TARGET_TABLE.LOAN_START_DATE,  
        TARGET_TABLE.LOAN_STATUS,  
        TARGET_TABLE.IS_ACTIVE,        
        TARGET_TABLE.RECORD_BEGIN_DATE,
        TARGET_TABLE.RECORD_END_DATE
    )
    SELECT
        SOURCE_TABLE.LOAN_NUMBER,      
        SOURCE_TABLE.CUSTOMER_NAME ,   
        SOURCE_TABLE.LOAN_AMOUNT,      
        SOURCE_TABLE.LOAN_START_DATE,  
        SOURCE_TABLE.LOAN_STATUS,      

        TRUE,        
        CURRENT_TIMESTAMP(),
        NULL
    FROM 
        DB.SCHEMA.SOURCE_TABLE
    LEFT JOIN 
        DB.SCHEMA.TARGET_TABLE
            ON SOURCE_TABLE.LOAN_NUMBER = TARGET_TABLE.LOAN_NUMBER 
                AND TARGET_TABLE.IS_ACTIVE = TRUE
    WHERE 
        TARGET_TABLE.LOAN_NUMBER IS NULL;
        

    --Deactivating records which got deleted from Source
    UPDATE DB.SCHEMA.TARGET_TABLE
    SET
        TARGET_TABLE.IS_ACTIVE       = FALSE,
        TARGET_TABLE.RECORD_END_DATE = CURRENT_TIMESTAMP()
    WHERE
        TARGET_TABLE.IS_ACTIVE = TRUE
        AND NOT EXISTS (
            SELECT 1
            FROM DB.SCHEMA.SOURCE_TABLE
            WHERE SOURCE_TABLE.LOAN_NUMBER = TARGET_TABLE.LOAN_NUMBER
        );

END;
$$;



CALL DB.SCHEMA.LOAD_TARGET_TABLE_FROM_SOURCE();