CREATE OR REPLACE PROCEDURE DB.SCHEMA.LOAD_TARGET_TABLE()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER
AS
$$
DECLARE
    STREAM_STALE_STATUS BOOLEAN;
BEGIN
    DESCRIBE STREAM DB.SCHEMA.SOURCE_TABLE_STREAM;

    SELECT "stale"
    INTO :STREAM_STALE_STATUS
    FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()));

    IF (STREAM_STALE_STATUS = FALSE) THEN
        --Running the -Big Merge Operation
        
        RETURN 'I AM INSIDE';
    END IF;

    RETURN 'STREAM IS STALE';
END;
$$;

CALL DB.SCHEMA.LOAD_TARGET_TABLE();