CREATE OR REPLACE STREAM DB.SCHEMA.SOURCE_TABLE_STREAM ON TABLE DB.SCHEMA.SOURCE_TABLE;

DESCRIBE STREAM DB.SCHEMA.SOURCE_TABLE_STREAM;

SELECT "stale" FROM TABLE(RESULT_SCAN(LAST_QUERY_ID())) INTO :STREAM_STALE_STATUS;


SELECT * FROM DB.SCHEMA.SOURCE_TABLE_STREAM;


-- DROP STREAM DB.SCHEMA.SOURCE_TABLE_STREAM;