CREATE OR REPLACE TASK DB.SCHEMA.LOAD_TARGET_TABLE_TASK
    WAREHOUSE = DW_WH
    SCHEDULE = 'USING CRON */3 * * * * America/New_York'
    --stale 
    --no data 
AS
    CALL DB.SCHEMA.LOAD_TARGET_TABLE();




ALTER TASK DB.SCHEMA.LOAD_TARGET_TABLE_TASK RESUME;





EXECUTE TASK DB.SCHEMA.LOAD_TARGET_TABLE_TASK;


DESCRIBE TASK DB.SCHEMA.LOAD_TARGET_TABLE_TASK;




DROP TASK DB.SCHEMA.LOAD_TARGET_TABLE_TASK;